import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SessionProvider } from 'next-auth/react';
import { useReducer } from "react";
import { AppDispatchContext, AppStateContext } from "./containers/AppConainer";
import reducer, { initialState } from "./services/state/store";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session
}: Readonly<{
  children: React.ReactNode;
  session: any;
}>) {
  const [state, dispatch] = useReducer(reducer, initialState);

  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <SessionProvider session={session}>
          <AppStateContext.Provider value={state}>
            <AppDispatchContext.Provider value={dispatch}>
              {children}
            </AppDispatchContext.Provider>
          </AppStateContext.Provider>
      </SessionProvider>
    </body>
</html>
  );
}
